onerror {resume}
add list -width 20 /tb_top222/uut/clk
add list /tb_top222/uut/en
add list /tb_top222/uut/rst
add list /tb_top222/uut/y
add list /tb_top222/uut/x
add list /tb_top222/uut/ALUFN_i
add list /tb_top222/uut/ALUout_o
add list /tb_top222/uut/Nflag_o
add list /tb_top222/uut/Cflag_o
add list /tb_top222/uut/Zflag_o
add list /tb_top222/uut/Vflag_o
add list /tb_top222/uut/PWMout
add list /tb_top222/uut/X_i
add list /tb_top222/uut/Y_i
add list /tb_top222/uut/X_DCS
add list /tb_top222/uut/Y_DCS
add list /tb_top222/uut/sdc_pm/clk
add list /tb_top222/uut/sdc_pm/en
add list /tb_top222/uut/sdc_pm/rst
add list /tb_top222/uut/sdc_pm/x
add list /tb_top222/uut/sdc_pm/y
add list /tb_top222/uut/sdc_pm/ALUFN
add list /tb_top222/uut/sdc_pm/PWMout
add list /tb_top222/uut/sdc_pm/counterOut
add list /tb_top222/uut/sdc_pm/en_in
add list /tb_top222/uut/sdc_pm/EQUY_in
add list /tb_top222/uut/sdc_pm/PWMmode
add list /tb_top222/uut/sdc_pm/x_in
add list /tb_top222/uut/sdc_pm/y_in
add list /tb_top222/uut/sdc_pm/cntPM/clk
add list /tb_top222/uut/sdc_pm/cntPM/en
add list /tb_top222/uut/sdc_pm/cntPM/rst
add list /tb_top222/uut/sdc_pm/cntPM/EQUY
add list /tb_top222/uut/sdc_pm/cntPM/count
add list /tb_top222/uut/sdc_pm/cntPM/counter
add list /tb_top222/uut/sdc_pm/PWM_PM/clk
add list /tb_top222/uut/sdc_pm/PWM_PM/en
add list /tb_top222/uut/sdc_pm/PWM_PM/x
add list /tb_top222/uut/sdc_pm/PWM_PM/y
add list /tb_top222/uut/sdc_pm/PWM_PM/cnt_in
add list /tb_top222/uut/sdc_pm/PWM_PM/ALUFN
add list /tb_top222/uut/sdc_pm/PWM_PM/PWMout
add list /tb_top222/uut/sdc_pm/PWM_PM/EQUY
add list /tb_top222/uut/sdc_pm/PWM_PM/PWM1
add list /tb_top222/uut/sdc_pm/PWM_PM/PWM2
add list /tb_top222/uut/alu_pm/Y_in
add list /tb_top222/uut/alu_pm/X_in
add list /tb_top222/uut/alu_pm/ALUFN_i
add list /tb_top222/uut/alu_pm/ALUout_o
add list /tb_top222/uut/alu_pm/Nflag_o
add list /tb_top222/uut/alu_pm/Cflag_o
add list /tb_top222/uut/alu_pm/Zflag_o
add list /tb_top222/uut/alu_pm/Vflag_o
add list /tb_top222/uut/alu_pm/s_mat
add list /tb_top222/uut/alu_pm/c_vec
add list /tb_top222/uut/alu_pm/aluadd
add list /tb_top222/uut/alu_pm/alushift
add list /tb_top222/uut/alu_pm/alugic
add list /tb_top222/uut/alu_pm/ALUout
add list /tb_top222/uut/alu_pm/x_add
add list /tb_top222/uut/alu_pm/y_add
add list /tb_top222/uut/alu_pm/x_Logic
add list /tb_top222/uut/alu_pm/y_Logic
add list /tb_top222/uut/alu_pm/x_shifter
add list /tb_top222/uut/alu_pm/y_shifter
add list /tb_top222/uut/alu_pm/carry_list
add list /tb_top222/uut/alu_pm/Out_option
add list /tb_top222/uut/alu_pm/ALUFN_in
add list /tb_top222/uut/alu_pm/addlabel/y
add list /tb_top222/uut/alu_pm/addlabel/x
add list /tb_top222/uut/alu_pm/addlabel/sub_cont
add list /tb_top222/uut/alu_pm/addlabel/s
add list /tb_top222/uut/alu_pm/addlabel/cout
add list /tb_top222/uut/alu_pm/addlabel/sumi
add list /tb_top222/uut/alu_pm/addlabel/x_a
add list /tb_top222/uut/alu_pm/addlabel/y_a
add list /tb_top222/uut/alu_pm/addlabel/c_0
add list /tb_top222/uut/alu_pm/addlabel/ad/xi
add list /tb_top222/uut/alu_pm/addlabel/ad/yi
add list /tb_top222/uut/alu_pm/addlabel/ad/cin
add list /tb_top222/uut/alu_pm/addlabel/ad/s
add list /tb_top222/uut/alu_pm/addlabel/ad/cout
add list /tb_top222/uut/alu_pm/addlabel/fin(1)/lp3/xi
add list /tb_top222/uut/alu_pm/addlabel/fin(1)/lp3/yi
add list /tb_top222/uut/alu_pm/addlabel/fin(1)/lp3/cin
add list /tb_top222/uut/alu_pm/addlabel/fin(1)/lp3/s
add list /tb_top222/uut/alu_pm/addlabel/fin(1)/lp3/cout
add list /tb_top222/uut/alu_pm/addlabel/fin(2)/lp3/xi
add list /tb_top222/uut/alu_pm/addlabel/fin(2)/lp3/yi
add list /tb_top222/uut/alu_pm/addlabel/fin(2)/lp3/cin
add list /tb_top222/uut/alu_pm/addlabel/fin(2)/lp3/s
add list /tb_top222/uut/alu_pm/addlabel/fin(2)/lp3/cout
add list /tb_top222/uut/alu_pm/addlabel/fin(3)/lp3/xi
add list /tb_top222/uut/alu_pm/addlabel/fin(3)/lp3/yi
add list /tb_top222/uut/alu_pm/addlabel/fin(3)/lp3/cin
add list /tb_top222/uut/alu_pm/addlabel/fin(3)/lp3/s
add list /tb_top222/uut/alu_pm/addlabel/fin(3)/lp3/cout
add list /tb_top222/uut/alu_pm/addlabel/fin(4)/lp3/xi
add list /tb_top222/uut/alu_pm/addlabel/fin(4)/lp3/yi
add list /tb_top222/uut/alu_pm/addlabel/fin(4)/lp3/cin
add list /tb_top222/uut/alu_pm/addlabel/fin(4)/lp3/s
add list /tb_top222/uut/alu_pm/addlabel/fin(4)/lp3/cout
add list /tb_top222/uut/alu_pm/addlabel/fin(5)/lp3/xi
add list /tb_top222/uut/alu_pm/addlabel/fin(5)/lp3/yi
add list /tb_top222/uut/alu_pm/addlabel/fin(5)/lp3/cin
add list /tb_top222/uut/alu_pm/addlabel/fin(5)/lp3/s
add list /tb_top222/uut/alu_pm/addlabel/fin(5)/lp3/cout
add list /tb_top222/uut/alu_pm/addlabel/fin(6)/lp3/xi
add list /tb_top222/uut/alu_pm/addlabel/fin(6)/lp3/yi
add list /tb_top222/uut/alu_pm/addlabel/fin(6)/lp3/cin
add list /tb_top222/uut/alu_pm/addlabel/fin(6)/lp3/s
add list /tb_top222/uut/alu_pm/addlabel/fin(6)/lp3/cout
add list /tb_top222/uut/alu_pm/addlabel/fin(7)/lp3/xi
add list /tb_top222/uut/alu_pm/addlabel/fin(7)/lp3/yi
add list /tb_top222/uut/alu_pm/addlabel/fin(7)/lp3/cin
add list /tb_top222/uut/alu_pm/addlabel/fin(7)/lp3/s
add list /tb_top222/uut/alu_pm/addlabel/fin(7)/lp3/cout
add list /tb_top222/uut/alu_pm/loglabel/x
add list /tb_top222/uut/alu_pm/loglabel/y
add list /tb_top222/uut/alu_pm/loglabel/ALUFN
add list /tb_top222/uut/alu_pm/loglabel/ALUout
add list /tb_top222/uut/alu_pm/shiftlabel/x
add list /tb_top222/uut/alu_pm/shiftlabel/y
add list /tb_top222/uut/alu_pm/shiftlabel/dir
add list /tb_top222/uut/alu_pm/shiftlabel/res
add list /tb_top222/uut/alu_pm/shiftlabel/cout
add list /tb_top222/uut/alu_pm/shiftlabel/c_0
add list /tb_top222/uut/alu_pm/shiftlabel/th_l
add list /tb_top222/uut/alu_pm/shiftlabel/th_r
add list /tb_top222/uut/alu_pm/shiftlabel/q
configure list -usestrobe 0
configure list -strobestart {0 ps} -strobeperiod {0 ps}
configure list -usesignaltrigger 1
configure list -delta collapse
configure list -signalnamewidth 0
configure list -datasetprefix 0
configure list -namelimit 5
